### PR TITLE
Timer Fix on Decomp Source Code + Scripts

### PR DESCRIPTION
**Pull request by Jackobo-Chocobo**

### CODE REVIEW

**Comment by Rubberduckycooly** [comment]
As I stated with the script decomp comment, it adds a bunch of custom code to fix this issue. There is no way to 100% confirm that people have scripts downloaded, they may only have bytecode. Since this PR is very closely tied to that, I'll close it here as well. I *may* accept a PR if theres a lightweight way of doing it that doesn't involve scripts (like what I attempted to do), but until then I'll keep this closed

**Comment by Jackobo-Chocobo** [comment]
So maybe removing the repository that contains the scripts will be better

**Comment by PimpUigi** [comment]
> 
> 
> As I stated with the script decomp comment, it adds a bunch of custom code to fix this issue. There is no way to 100% confirm that people have scripts downloaded, they may only have bytecode. Since this PR is very closely tied to that, I'll close it here as well. I _may_ accept a PR if theres a lightweight way of doing it that doesn't involve scripts (like what I attempted to do), but until then I'll keep this closed

To be fair to you RDC, your solution worked on Restarts, and Lampposts (if Sonic died the milliseconds was recorded properly)
It was only an issue on Time Warps. So perhaps you have a lightweight solution for that in mind???

**Comment by PimpUigi** [comment]
Just in case it wasn't clear, the current decomp resetting the timer during Time Warps is a worse solution than the original restart milliseconds issue. 
Temporarily having a solution that requires the external scripts is better than having this be worse than the Steam release.

One does have to wonder how Mobile fixed it. But regardless, a revert of your current solution is worst case scenario, a minor improvement. And a heavy solution is at least here temporarily speaking.

**Pull request closed without merging**
