### PR TITLE
Porting to PS Vita

### PR DESCRIPTION
**Pull request by Xeeynamo**
# Sonic CD on PS Vita

The expectation is to run Sonic CD '11 decompilation natively on PS Vita devices (eg. PS Vita and PS Vita TV) with the same level of quality that you get when you run the same codebase on PC. The objective is also to minimise the amount of code changes and plan ahead future console portings.

I do not own a memory card for my PS Vita (it's a long story) so I can not test the game myself. I am relying on Vita3K emulator and to some friends to test new builds once in a while.

## Additions

* Adds `SonicCD.Vita` in the project's root. There is where you should expect all the PS Vita asset needed to trigger a build.
* The compilation file is in `SonicCD.Vita/build.sh` and uses Docker to virtually add zero configuration to build.
* The script `SonicCD.Vita/build-internal.sh` is called by the Docker image and it will automatically download all the dependencies needed for the compilation. The generated `SonicCD.vpk` is the application you should expect to install on your console.

## Code changes

* Updates `.gitignore` to ignore the artifacts created by the PS Vita build process.
* The PS Vita expects an absolute path that I hardcoded for `ux0:data/SonicCD/` where it expects to read and write PC assets. To minimise the amount of code changes, I defined a `BASE_PATH` that is pre-pended to every file path (eg. `CheckRSDKFile(BASE_PATH "Data.rsdk")`). That can be used for future portings that requires an absolute path as well.
* Adds `#include <string>` in `Ini.cpp` as it is required for `std::find`.
* Defines `M_PI` as [it is not defined by standard from `math.h`](http://www.cplusplus.com/forum/beginner/105176/)
* Evaluate `Engine.sdlEvents.window.event` only when `Engine.sdlEvents.type` is `SDL_WINDOWEVENT` to prevent to process events that are not really supposed to operate on the window.

## Known problems

* ~No full-screen support. The reason is that the actual full-screen is not pixel perfect. PS Vita have a resolution of 960x544. Considering that Sonic CD runs at Nx240, the resolution needs to be scaled by `2.26`. Not a number we pixel fetish like. I am considering to do a bordered full screen by centering the image for now. But I will wait for a feedback.~ Set horizontal resolution from `426` to `480` for PS Vita only.
* ~There is no video playback support. I commented everything related to libtheora in `Video.hpp` and `Video.cpp` for the sake of having a working executable in a short time. I plan to revert that change before marking this PR as ready.~ FIXED.
* ~There is a softlock in `Scene.cpp` line `755` where for some reason it is looping indefinitely. I did not commit the change, but I had to add a counter from `32` to `0` to prevent to loop for ever. I am still not sure what's the cause of it as it is not happening on PC. Adding those lines makes the game working just fine without (apparently) affecting collisions.~ FIXED
* ~Sonic sprite is not showing at all on screen. I am not yet sure what causes the issue.~ FIXED

## Planned changes

We do not have a CI/CD to automatically compile new builds on code changes, am I right? I was planning to use GitHub Actions to generate N artifacts (where N is the amount of platforms) on every push on master. This will probably be a different Pull Request as I plan to automatically generate builds also for PC. Let me know if this is a wanted feature.

### CODE REVIEW

**Comment by Rubberduckycooly** [comment]
- It's really cool to see this getting ported to other platforms so I'm a big fan of that!
- Pretty much in agreement on every one of the code changes, I think they're all great!
- RSDK tends to use Nx240 for base resolution so its a bit of a pain yeah, I think most of the game should work fine if you bumped it up slightly on vita, but it'd look a bit odd for sure, especially stuff like the hud which has the constant of 240 for height in the scripts rather than "screen.height"
- The scene.cpp softlock *may* be to do with sign of `char`, since most platforms have it signed, but its not totally unheard of for some platforms to have char as an unsigned value for whatever reason, I know xcode has the option for that at least.
- Not sure what the issue could be with the sonic sprite displaying

I'm going to push most of the more minor code changes to master so that they're avaliable for people when/if they choose to make other forks/ports of the repo

And you are correct we dont have automatic builds, and I honestly hadn't even considered it but thats a really good idea to add tbh, since I've made a few minor tweaks and etc in the last few days but obviously haven't made any new builds, so if you could add that, it'd be great!

**Comment by Xeeynamo** [comment]
You were right, the toolchain I am using defines a `char` as `unsigned`. Appending `-fsigned-char` fixes not only that issue but also makes Sonic sprite visible 🎉
image

I am now dealing with the remaining issues.

**Comment by Rubberduckycooly** [comment]
sweeeet!

**Comment by Xeeynamo** [comment]
I feel confident that this pull request is ready to be reviewed. The last bug that prevented me to merge it, the time attack section freezing, was fixed by @isage . 

I am aware that there is a second porting from @SonicMastr and I became aware of it after creating this PR. As the amount of changes I made here are minimal, it would be good if his port would be rebased upon this so we can receive his code proposal as well!

Small tip about this PR: I added a `.github/workflow/build.yml`. This allows GitHub Actions to build and create an installer of Sonic CD at every push on master. The artifact will only be visible by you, but you're free to take it and publish when you feel ready to do so. The reason why I did not decide to publish it automatically it's because I do not know the frequency you wanted to release new builds.

PS. I am working to automate Windows builds, but the old project format gives me problems :'D

**Comment by Rubberduckycooly** [comment]
Looks good! the only change I'd say to add before I merge it would be to remove any existing assets like icons or etc that are from the game (either remove them or replace them with a black image or something similar) that way there shouldn't be even the slightest issue in terms of legality of providing assets that are game related.

**Comment by Xeeynamo** [comment]
> Looks good! the only change I'd say to add before I merge it would be to remove any existing assets like icons or etc that are from the game (either remove them or replace them with a black image or something similar) that way there shouldn't be even the slightest issue in terms of legality of providing assets that are game related.

Done 👍 I completely removed them from the git history of my PR.

**Pull request merged**
